version: '3'

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:18.0.0"
    ports: ["8888:8080"]
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin